services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=smieci-wywoz-network"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - smieci-wywoz-network
    labels: 
      - "traefik.enable=true"

  app:
    image: $REGISTRY_IMAGE:$IMAGE_TAG
    restart: unless-stopped
    # depends_on:
    #   - db
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
    secrets:
      - db_password
    networks:
      - smieci-wywoz-network
    working_dir: /var/www/html
    volumes:
      - ./backups:/var/www/html/storage/backups
      - ./logs:/var/www/html/storage/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.rule=PathPrefix(`/api/v1`) && Host(`smieci-wywoz.pl`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  # ? Zewnętrzny serwer bazy danych
  # db:
  #   image: yobasystems/alpine-mariadb
  #   restart: unless-stopped
  #   secrets:
  #     - db_password
  #   environment:
  #     MYSQL_HOST: ${MYSQL_HOST}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD_FILE: /run/secrets/db_password
  #   networks:
  #     - ccc-network
  #   volumes:
  #     - ./db_data:/var/lib/mysql

secrets:
  db_password:
    file: ./secrets/db_password


networks:
  smieci-wywoz-network:
    driver: bridge