services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - smieci-wywoz-network
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  db:
    image: yobasystems/alpine-mariadb
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: smieci-wywoz
    networks:
      - smieci-wywoz-network
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    networks:
      - smieci-wywoz-network

volumes:
  db_data: {}

networks:
  smieci-wywoz-network:
    driver: bridge